/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidmadgwick_nativefunction_IMUInterface */

#ifndef _Included_com_example_androidmadgwick_nativefunction_IMUInterface
#define _Included_com_example_androidmadgwick_nativefunction_IMUInterface
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_example_androidmadgwick_nativefunction_IMUInterface_initMadgwick
  (JNIEnv *, jclass);
/*
 * Class:     com_example_androidmadgwick_nativefunction_IMUInterface
 * Method:    updateIMU
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_com_example_androidmadgwick_nativefunction_IMUInterface_updateIMU
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
